pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - status-success=test (ubuntu-latest, 10.x)
      - status-success=test (ubuntu-latest, 12.x)
      - status-success=test (windows-latest, 10.x)
      - status-success=test (windows-latest, 12.x)
    actions:
      merge:
        method: merge
