git:
  depth: 10
sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 12
  - 10
  - 8

before_install:
  - node -v
  - npm -v
  - yarn -v

script:
  - yarn test
  - codecov
